apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-istio-base
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: base
          addonChartName: istio-base
          addonChartVersion: 1.18.3
          addonChartNamespace: istio-system
          addonChartRepository: https://istio-release.storage.googleapis.com/charts
        selector:
          matchExpressions:
            - key: enable_istio
              operator: In
              values: ['true']
    - clusters:
        values:
          addonChart: istiod
          addonChartName: istio-discovery
          addonChartVersion: 1.18.3
          addonChartNamespace: istio-system
          addonChartRepository: https://istio-release.storage.googleapis.com/charts
        selector:
          matchExpressions:
            - key: enable_istio
              operator: In
              values: [ 'true' ]
    - clusters:
        values:
          addonChart: gateway
          addonChartName: istio-internal-gateway
          addonChartVersion: 1.18.3
          addonChartNamespace: istio-system
          addonChartRepository: https://istio-release.storage.googleapis.com/charts
        selector:
          matchExpressions:
            - key: enable_istio_internal_gateway
              operator: In
              values: [ 'true' ]
    - clusters:
        values:
          addonChart: gateway
          addonChartName: istio-external-gateway
          addonChartVersion: 1.18.3
          addonChartNamespace: istio-system
          addonChartRepository: https://istio-release.storage.googleapis.com/charts
        selector:
          matchExpressions:
            - key: enable_istio_external_gateway
              operator: In
              values: [ 'true' ]
    - clusters:
        values:
          addonChart: istio-resources
          addonChartName: istio-resources
          addonChartVersion: 1.0.0
          addonChartNamespace: istio-system
          addonChartRepository: https://github.com/The9thLime/terraform-aws-eks/tree/feat/gitops-bridge/charts/istio/
        selector:
          matchExpressions:
            - key: enable_istio
              operator: In
              values: [ 'true' ]
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChartName}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{metadata.annotations.addons_repo_basepath}}values/istio/{{values.addonChartName}}/values.yaml
      destination:
        namespace: '{{values.addonChartNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # For handling big CRDs.
          - ApplyOutOfSyncOnly=true
