vpa:
  enabled: false
  updater:
    enabled: false
nodeSelector:
  CriticalAddonsOnly: "true"  # from critical_addons_node_selector
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    effect: "NoSchedule"
    value: "true"  # from critical_addons_node_tolerations
controller:
  nodeSelector:
    CriticalAddonsOnly: "true"  # from critical_addons_node_selector
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      effect: "NoSchedule"
      value: "true"  # from critical_addons_node_tolerations
dashboard:
  nodeSelector:
    CriticalAddonsOnly: "true"  # from critical_addons_node_selector
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      effect: "NoSchedule"
      value: "true"  # from critical_addons_node_tolerations
